server:
  port: 8081

security:
    oauth2:
        resource:
            jwt:
                key-uri: http://localhost:9999/oauth/token_key

logging:
  level:
    org.springframework.security: DEBUG