server:
  port: 8081

security:
    oauth2:
        resource:
            jwt:
                key-uri: http://localhost:9999/oauth/token_key

spring:
    social:
        app:
            url: http://localhost:8080/api
        dropbox:
            appId: 
            appSecret: 
        google:
            appId: 
            appSecret: 

logging:
  level:
    org.springframework.security: DEBUG